### ISSUE TITLE
Users' feedback - TODO fixes

### ISSUE THREAD

**Issue by 234752** [HaMaKac/TeamProject#1]
# Users' remarks

- [x] 1. the only place where is back arrow is Achievements while other pages don't have it
- [ ] 2. display all already planted flowers
- [x] 3. Unnecessary repetition of the section title in Information.
- [x] 4. Illegible white font in "Available money" and $ inconsistency (there is no $ in "Available money").
